pipeline {
    agent any
    options { disableConcurrentBuilds() }
    stages {
        stage('setting up clean environment') {
            steps {
                sh 'pwd; ls'
                sh 'PATH=$PATH:/usr/local/bin vagrant destroy -f || true'
                sh 'PATH=$PATH:/usr/local/bin vagrant up'
            }
        }
        stage('build') {
            steps {
                sh 'PATH=$PATH:/usr/local/bin vagrant up'
            }
        }
    }
    post {
        always {
                sh 'PATH=$PATH:/usr/local/bin vagrant halt'
        }
    }
}
