pipeline {
    agent { label 'macos10.11' }
    options { disableConcurrentBuilds() }
    stages {
        stage('setting up clean environment') {
            steps {
                dir('ci/10.11') {
                  sh 'cp -r ../src/* .'
                  sh 'PATH=$PATH:/usr/local/bin vagrant destroy -f || true'
                  sh 'PATH=$PATH:/usr/local/bin vagrant up'
                }
            }
        }
        stage('build') {
            steps {
                dir('ci/10.11') {
                  sh 'PATH=$PATH:/usr/local/bin vagrant up'
                }
            }
        }
    }
    post {
        always {
                dir('ci/10.11') {
                  sh 'PATH=$PATH:/usr/local/bin vagrant halt'
                }
        }
    }
}
