# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "macos_10.11"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
  end

  config.vm.synced_folder "../../", "/vagrant", type: "rsync"  # the normal sharing uses guest extensions, which don't exist for macOS and virtualbox
#  config.vm.provision "shell", path: "update-os.sh"
#  config.vm.provision :reload
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
  config.vm.provision "shell", inline: "mkdir -p /vagrant/build; chown -R vagrant /vagrant/build"
  config.vm.provision "shell", path: "run.sh", privileged: false
end
